modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="gyisti"
version="0.1.2"
displayName="Gyisti"
displayURL="https://github.com/NoteSwiper"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="787noteswiper, user, MCreator"
description="huh?"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.gyisti]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.gyisti]]
    modId="cloth_config"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gyisti]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gyisti]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

